//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    namespace persistence
    {
        public partial class bd_alumnosEntities1 : DbContext
        {
            public bd_alumnosEntities1()
                : base("name=bd_alumnosEntities1")
            {
            }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                throw new UnintentionalCodeFirstException();
            }

            public virtual DbSet<administradores> administradores { get; set; }
            public virtual DbSet<Alumnos> Alumnos { get; set; }
            public virtual DbSet<Clases> Clases { get; set; }
            public virtual DbSet<Clases_Tema> Clases_Tema { get; set; }
            public virtual DbSet<Profesores> Profesores { get; set; }
            public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
            public virtual DbSet<Temas> Temas { get; set; }
        }
    }

