//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesores
    {
        public int legajo { get; set; }
        public string pasword { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public long dni { get; set; }
        public byte[] telefono { get; set; }
        public byte[] email { get; set; }
        public int anio_ingreso { get; set; }
    }
}
